RaytenCorp/Rayten

Content.Server/Chemistry/EntitySystems/InjectorSystem.cs
Resources/Prototypes/Entities/Clothing/Head/base_clothinghead.yml

- Добавил дополнительную проверку, если идет действие введения иглы в персонажа и он надел одежду с защитой от инъекции, то действие не выполнится.
- Исправлена защита от разгерметизации в скафандрах. 
**Медиа**
**Проверки**
**Изменения**
:cl: Menttares
- fix: Исправлены скафандры EVA и инъекция шприцов

Fix: исправлены скафандры eva и инъекция шприца

---

Content.Server/Chemistry/EntitySystems/HypospraySystem.cs
Content.Server/Chemistry/EntitySystems/InjectorSystem.cs

Немного поменял логику проверки защиты от инъекции 
**Медиа**
**Проверки**
**Изменения**
:cl: Menttares
- fix: Исправлена инъекция на существах

Fix: Исправил инъекцию на мобах

---

Content.Server/Discord/Webhooks/WebhookBans.cs
Content.Server/Entry/EntryPoint.cs

https://github.com/VanillaStation14/VanillaStation/issues/4#issue-2456716222
Очередное исправление вебхука банов, надеюсь, что окончательное.
**Медиа**
**Проверки**
**Изменения**
:cl: Menttares
- fix: Мелкие исправления

Исправил ошибку вебхука банов

---

Content.Server/Chemistry/EntitySystems/HypospraySystem.cs
Content.Server/Chemistry/EntitySystems/InjectorSystem.cs

Поменял чуть-чуть логику, теперь все должно работать
**Медиа**
**Проверки**
**Изменения**
:cl: Menttares
- fix: Исправлено инъекция на животных

Исправлена иньекция на животных

---

Content.Client/Administration/UI/AdminMenuWindow.xaml.cs

Фикс неудобного размера менюшки админа на F7
Неудобно было 
Content.Client/Administration/UI/AdminMenuWindow.xaml.cs 
MinSize = new Vector2(650, 250);
MinSize = new Vector2(780, 370);
Нету
Content.Client/Administration/UI/AdminMenuWindow.xaml.cs 
MinSize = new Vector2(650, 250);
MinSize = new Vector2(780, 370);

Фикс неудобного размера менюшки

---

Content.Server/Radio/EntitySystems/RadioSystem.cs

Добавляет приписку в гарнитуру
https://github.com/VanillaStation14/VanillaStation/issues/18#issue-2471164554
Сделал на скорую руку, особо не тестировал, если ошибки будут, пишите.

Добавление профессии в рации

---

Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
Resources/Locale/ru-RU/vanilla/Skill-system.ftl
Resources/Prototypes/Entities/Objects/Specific/Medical/healing.yml
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/Medical/cryo_pod.yml

Изменены навыки химии и медицины
навык медицины теперь затрагивает намного больше аспектов медицины, а химия не лезет туда, где логично было бы использовать медицину.
Помимо прочего, довольно много кода было зарефакторено, улучшенно и теперь даже нельзя мензурки сувать в центрифугу. 
:cl:
- tweak: Изменены навыки химии и медицины

chem med skill update

---

.github/workflows/check-crlf.yml
Resources/Maps/Shuttles/Торговый пост.yml
Resources/Prototypes/Entities/Stations/base.yml
Tools/check_crlf.py

Обновил торговый пост
В целом должно улучшить взаимодействие с торговым постом за счёт системы конвейеров. Правда потребуется также переделать шаттл карго, этого пока что не хватает
обновил crlf чекер чтобы он принимал русские названия файлов. (Необходимо т.к. гриды на консоли шаттлов в игре имеют то название, какое есть у файла)
:cl: tfmb
- tweak: Изменён торговый пост!

tradepost update

---

Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml

Звуки чата и смерти офицеров СБ, Вардена и ГСБ.
:cl:
- add: Добавлены звуки сообщений и смерти офицеров СБ, Вардена и ГСБ.

крутые звуки для офицеров СБ

---

Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/roles.yml
Resources/Prototypes/Vanilla/Entities/Mobs/Player/ShuttleRoles/settings.yml
Resources/Prototypes/Vanilla/Entities/Objects/Consumable/Food/BlueSky.yml
Resources/Prototypes/Vanilla/Reagents/BreakingBad.yml
Resources/Prototypes/Vanilla/Recipes/Cooking/BlueSkyRecipe.yml
Resources/Prototypes/Vanilla/Recipes/Reactions/BreakingBad.yml

Починил навыки у варщиков, переместив компоненты в settings.yml
Починит их
Зачем
Зачем
Зачем
:cl:
- fix: Исправлены навыки у нелегальных химиков
- tweak: Теперь эфедронекс требует дэзоксиэфедрин, но его ускорение на 0.15 больше.

фикс навыков варщиков

---

Resources/Prototypes/ai_factions.yml

фикс фаркции центком

---

Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
Content.Shared/Vanilla/Skill/components/SkillComponent.cs
Resources/Locale/ru-RU/vanilla/Skill-system.ftl
Resources/Prototypes/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/Entities/Objects/Specific/atmos.yml
Resources/Prototypes/Entities/Objects/Tools/tools.yml
Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/Entities/Structures/Machines/gravity_generator.yml
Resources/Prototypes/Entities/Structures/Piping/Atmospherics/binary.yml
Resources/Prototypes/Entities/Structures/Piping/Atmospherics/trinary.yml
Resources/Prototypes/Entities/Structures/Piping/Atmospherics/unary.yml
Resources/Prototypes/Entities/Structures/Power/Generation/PA/control_box.yml
Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/containment.yml
Resources/Prototypes/Entities/Structures/Power/Generation/Singularity/emitter.yml
Resources/Prototypes/Entities/Structures/Power/Generation/ame.yml
Resources/Prototypes/Entities/Structures/Power/Generation/portable_generator.yml
Resources/Prototypes/Entities/Structures/Power/apc.yml
Resources/Prototypes/Entities/Structures/Shuttles/station_anchor.yml
Resources/Prototypes/Entities/Structures/Wallmounts/air_alarm.yml

Добавлен новый навык - инженерия
Он отвечает за электронику и атмос
0 ур. - минипакман
1 ур. - суперпакман, пакман, логическая система, ЛКП, газовые насосы, газовый фильтр, газовый смеситель
2 ур. - ДАМ, Солнечные панели, Станционный якорь, генератор гравитации, монитор электроэнергии, монитор воздушной сигнализации, газоанализатор, нагреватель, охладитель
3 ур. - Воздушная сигнализация, (эмиттеры, силовые барьеры, УЧ)...
весь код спрятан, тут только прототипы и компоненты
их нет
:cl: TFMB
- add: Добавлен новый навык "инженерия"

New skill - engineering

---

Resources/Prototypes/Entities/Objects/Specific/Mech/mech_construction.yml
Resources/Prototypes/Entities/Structures/Doors/Airlocks/base_structureairlocks.yml
Resources/Prototypes/Entities/Structures/Power/apc.yml
Resources/Prototypes/Recipes/Construction/utilities.yml

Фиксы навыку приборостроение
был баг с отображением запроса навыка на вещи, на которые навык не требуется, например на открытие панелей у шлюзов

more fixes

---

Resources/Prototypes/Loadouts/loadout_groups.yml

Забыл добавить Дешёвые Солнцезащитные очки в loadout_groups.yml XD

Cheap sunglasses hotfix

---

Content.Shared/CCVar/CCVars.Chat.cs
Resources/ConfigPresets/Vanilla/Vanilla.toml
Resources/Maps/Shuttles/ShuttleEvent/cookers_shuttle.yml

Добавил йод, декали, изменил рецепт в шаттле варщиков. Увеличил лимит букв у консоли связи до 850
Улучшает гейплей
Зачем
Зачем
Их нет
:cl:
- tweak: Увеличена граница у консоли связи до 850 символов.
- fix: Исправлен шаттл нелегальных химиков. Теперь там есть йод, направленный вентилятор, кнопка для открытия шлюзов и подкорректирован рецепт.

Очень мелкие фиксы

---

Content.Server/Administration/Systems/BwoinkSystem.cs
Content.Server/Chat/Managers/ChatManager.cs
Resources/Locale/ru-RU/vanilla/chat.ftl
Resources/Prototypes/Corvax/Maps/cuteinstallation.yml

Разные цвета для оос чата и ахелпов для разных админчиков
потому что
пришлось влезть в офовские менеджеры но мне пофиг
впадлу
:cl:
- add: Добавлены разные цвета для оос чата и ахелпов для разных администраторов

Цвета для ООС и ахелпов

---

.github/workflows/publish.yml
Tools/actions_changelog_rss.py

Добавлен авточенжлог
потому что я задолбался его добавлять вручную
:cl:
- add: Добавлен авточенжлог
- remove: Удалено веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

авточенжлог

---

Tools/actions_changelogs_since_last_run.py

Добавлен авточенжлог
:cl:
- add: Добавлен авточенжлог
- remove: Удалено веселье!
- tweak: Изменено веселье!
- fix: Исправлено веселье!

autochangelog

---

Tools/actions_changelogs_since_last_run.py

autochangelogfix

---

Resources/Locale/ru-RU/vanilla/Skill-system.ftl

механ голосования
теперь не такая топорная система
:cl:
- fix: Голосование за доп. очки теперь не учитывает гостов.
- tweak: Доп. о.н. теперь выдаются по формуле 9 + (10-количество игроков)*6.
- remove: Теперь главы получают столько же, сколько и остальной экипаж.

ezmode vote final version

---

Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
Resources/Prototypes/Entities/Objects/Specific/chemical-containers.yml
Resources/Prototypes/Entities/Objects/Specific/chemistry.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Snipers/snipers.yml

изменены навык химии и медицины, теперь как на вики:
https://vanilla-station.ru/w/%D0%9D%D0%B0%D0%B2%D1%8B%D0%BA%D0%B8
:cl:
- tweak: Сильно изменены навыки химии и медицины - подробнее на вики

Skillsrework

---

Content.Server/Vanilla/Skill/Components/GunCanBeFallComponent.cs
Content.Server/Vanilla/Skill/Components/MeleeTrainerComponent.cs
Content.Shared/Construction/Prototypes/ConstructionPrototype.cs
Content.Shared/Vanilla/Skill/components/RequiresSkillComponent.cs
Content.Shared/Vanilla/Skill/components/SkillComponent.cs
Content.Shared/Vanilla/Skill/components/SkillLearnerComponent.cs
Resources/Prototypes/Entities/Mobs/Species/base.yml

Навыки допилены, осталось совсем немного
потому
Переделана техническая часть системы навыков, теперь все намного более типизировано и быстрее;
компонент skill разделён на два компонента; 
:cl:
- add: Очки навыков за голосование теперь рассчитываются по формуле 162/количество игроков
- add: Теперь даётся медицинский опыт за лечение (с помощью наборов для ушибов, бинтов и так далее) и использование дефибриллятора
- add: Скорость использования инструментов (челюсти жизни, отвёртки, гаечные ключи итд) теперь зависит от уровня строительства
- add: Теперь имея 3 уровень инженерии есть 75% шанс избежать удара током
- add: Спарринг на боксёрских перчатках даёт опыт в навык ближнего боя.

yay release version of skill system

---

Content.Client/_CorvaxNext/Footprints/FootprintSystem.cs
Content.Server/_CorvaxNext/Footprints/FootprintCleanEvent.cs
Content.Server/_CorvaxNext/Footprints/FootprintOwnerComponent.cs
Content.Server/_CorvaxNext/Footprints/FootprintSystem.cs
Content.Shared/_CorvaxNext/Footprints/FootprintChangedEvent.cs
Content.Shared/_CorvaxNext/Footprints/FootprintComponent.cs
README.md

Добавлен копирайт и лицензия на все системы и компоненты из [этого пра](https://github.com/RaytenCorp/VanillaStation/pull/132) и на readme
Нарушение лицензии

dmca moment

---

Resources/Maps/Vanilla/CCOfficial_Shuttle.yml

На этот раз должно быть без ошибок. Шаттл замаплен Воронкой.
Добавлен шаттл ПЦК в сборку.
Для удобства отправки Представителя ЦентКом на станцию; Чтобы у него был свой шаттл, и не надо было лететь на боевом.
Перенёс файл из загрузок в вилку.
:cl: Voroncka2000
- add: Добавлен отдельный шаттл для ПЦК.

Добавлен шаттл ПЦК

---

Resources/ConfigPresets/Vanilla/Vanilla.toml

1. Урон от навыка ближнего боя изменен с 60%/80%/100%/120% до 30%/60%/90%/120%
2. Время на цк (предлобби) - уменьшено на 105 секунд , время в лобби увеличено на 105 секунд.
:cl:
- tweak: Урон от навыка ближнего боя изменен с 60%/80%/100%/120% до 30%/60%/90%/120%
- tweak: Время на цк (предлобби) - уменьшено на 105 секунд , время в лобби увеличено на 105 секунд.

ребаланс времени в лобби и в ендгейме

---

Resources/Locale/ru-RU/vanilla/discord-auth.ftl

:cl:
- tweak: Возвращена дискорд авторизация, но теперь она не обязательна для захода на сервер.

возвращена дискорд-авторизация

---

Resources/Locale/ru-RU/vanilla/ui/background.ftl
Resources/Prototypes/Vanilla/Backgrounds/roles/ghostroles/NukeOpsTeam.yml

:cl:
- add: Добавлены предыстории! Пока что для гост ролей.
- add: Добавлено 4 предыстории для скелета
- add: Добавлено 4 предыстории для одинокого ядерного оперативника
- add: Добавлено 9 предысторий для ядерных оперативников.

background v0.2.1

---

Resources/Prototypes/Catalog/Cargo/cargo_armory.yml

https://discord.com/channels/1236324156165980311/1368302263856267335
https://discord.com/channels/1236324156165980311/1368302263856267335
:cl:
- tweak: Понижена цена имплант-трекеров с 15.000 до 7.000!

Удешевление трекеров

---

Resources/Locale/ru-RU/vanilla/ui/background.ftl

:cl:
- add: Добавлена демка предысторий капитана в которой можно потыкать кнопочки.

предстория

---

Content.Server/Vanilla/GameTicking/Rules/Components/WhiteoutComponent.cs
Content.Server/Vanilla/GameTicking/Rules/WhiteoutRuleSystem.cs
Resources/Prototypes/Corvax/secret_weights.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
Resources/Prototypes/secret_weights.yml

:cl:
- tweak: Увеличены резисты зимних курток, чуть ослаблена обычная фаза бури. Уменьшен шанс выпадения режима вдвое

Правки в балансе бури

---

Content.IntegrationTests/Tests/PostMapInitTest.cs
Resources/Prototypes/Corvax/Entities/Objects/Misc/tiles.yml
Resources/Prototypes/Vanilla/Backgrounds/ghostroles/ClosetSkeletonBackgrounds.yml
Resources/Prototypes/Vanilla/Backgrounds/ghostroles/TDM/TDMBackgrounds.yml
Resources/Prototypes/Vanilla/Roles/TDM_Gear.yml
Resources/Prototypes/Vanilla/TDM_Arenas.yml
Resources/Prototypes/game_presets.yml

:cl:
- add: Теперь все снова пацифисты в конце раунда
- add: В конце раунда теперь приходит инвайт в тдм, можно отказаться
- add: Добавлена новая равлекуха для гостов, теперь госты могут играть тдм на отдельном гриде
- add: meet the class system in tdm! В тдм добавлены классы: скаут, солдат, хэви, медик, снайпер, шпион; боже храни предыстории
- add: Теперь в конце тдма выводится таблица результатов и можно пофлексить статами

прокачка тдма

---

Resources/Locale/ru-RU/vanilla/prototypes/entities/weapons/guns/dominator_component.ftl
Resources/Prototypes/Damage/modifier_sets.yml
Resources/Prototypes/Entities/Mobs/Cyborgs/base_borg_chassis.yml
Resources/Prototypes/Entities/Mobs/Species/skeleton.yml

Тупой 30%
Режущий 50%
Колющий 30%
Урон от электричества увеличен на 20%
Скелеты теперь получают урон от библии 50хп и святой воды (хз сколько)
Хп скелетов уменьшено с 150 до 60.
:cl:
- add: Добавлены резисты для киборгов
- tweak: ХП скелетов уменьшено со 150 до 60, скелеты теперь получают урон от библии и святой воды.

разные приколы

---

Resources/Prototypes/Entities/Objects/Misc/identification_cards.yml

:cl:
- add: карта детектива теперь автокарта

карта детектива теперь автокарта

---

Resources/Prototypes/Entities/Mobs/NPCs/elemental.yml
Resources/Prototypes/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/armblade.yml
Resources/Prototypes/Entities/Objects/Weapons/Melee/cult.yml
Resources/Prototypes/Vanilla/Entities/Objects/Weapons/Guns/Battery/battery_guns.yml

:cl:ч
- tweak: Стоимость энергии за выстрел доминаторов уменьшена на 40%
- fix: Слаймы и рудокрабы теперь считаются опасными, армблейд геноркрада стал опасным предметом 3 уровня, оружие культа теперь имеет 1 класс опасности.

доминаторские фиксы
